version: "3.9"
services:
  postgresql_b1_l19:
    container_name: 'postgresql_b1_l19'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
    - ./data/b1:/var/lib/postgresql
  
  postgresql_b2_l19:
    container_name: 'postgresql_b2_l19'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
    - ./data/b2:/var/lib/postgresql
  
  postgresql_b3_l19:
    container_name: 'postgresql_b3_l19'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    volumes:
    - ./data/b3:/var/lib/postgresql
  php_l19:
    build:       Docker/PHP
    working_dir: /var/www/app
    volumes:
    - ./app:/var/www/app
